### PR TITLE
Add a new horizontal banner

### PR DESCRIPTION
**Pull request by Alexqw**
Opening a PR as I don't have commit perms for this repo.

---Alex

------
The lettering originates from Orbitron (OFL)[1] and was adjusted from there.

Props to Falko Kaule for meaningful critiques.

[1] https://fonts.google.com/specimen/Orbitron

### CODE REVIEW

**Comment by hanke** [comment]
INFO: origin is under Open Font License

http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web

**Comment by hanke** [comment]
I like it!

**Comment by Alexqw** [comment]
@hanke Yup, which is why I put (OFL) after the font name. ;-)

---Alex

**Comment by Alexqw** [comment]
@hanke @yarikoptic Updated PR with v8 which uses original DL logo.

---Alex

**Pull request merged**
